# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy - Development

on:
  push:
    branches:
      - develop
      - 'ai-**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      app-name: valerianverona-dev
    secrets:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23A04D24B4224724895068CC64EF1B48 }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A307F732A95F470C98B3194C6536BF78 }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_00CD1132FB35471487D980E6F3663C56 }}